[project]
name = "ptk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansys-mapdl-reader>=0.55.1",
    "h5py>=3.15.1",
    "pyvista[all]>=0.46.4",
    "sexpdata>=1.0.2",
    "vtk>=9.5.2",
]
