[project]
name = "pyvtk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "h5py>=3.15.1",
    "pyvista[all]>=0.46.4",
    "vtk>=9.5.2",
]
